### ISSUE TITLE
[BUG]: Imager Username Details not persistant uppon booting

### ISSUE THREAD

**Issue by bencunn77** [raspberrypi/rpi-imager#1362]
### What happened?

After upgrading to the 2.0.0 Imager I have pre-configured the device hostname, WIFI, username & password but when I boot the device first I have to enter all the details again, the WIFI details pull through but for some reason the username details do not pull through. it worked on the old version I believe but for some reason it doesnt work now.
Not too sure what logs or that I can provide, still learning these so anything I can provide I will try!

### Version

2.0.0 (Default)

### What host operating system were you using?

Windows

### Host OS Version

25H2 (OS Build 26200.7171)

### Selected OS

Raspberry Pi OS (64-bit)

### Which Raspberry Pi Device are you using?

Raspberry Pi 5, 500, and Compute Modules 5

### What kind of storage device are you using?

microSD Card in an internal reader

### OS Customisation

- [x] Yes, I was using OS Customisation when the bug occurred.

### Relevant log output

```shell

```

**Comment by bakerhillpins** [comment]
I'm seeing something similar, However, I'm using the 1.9.6 Imager.

We can't get a CM5 headless image to work. After using the Imager we must boot the system up with a keyboard/mouse/monitor. It boots up and hangs asking for us to apply all of the Keyboard and Username/Password changes that should have been applied via the Imager Settings.

I used this same version a month ago (I've updated nothing on my PC) to write out an image and it worked just fine.  I am assuming at that earlier time the Image used was a Trixie dated 10/1/25. Currently, it's referencing a Trixie image from 11/14/25.

If we build a Raspberry Pi 4 headless image it works correctly on 1st boot.

I also tried downloading the previous 10/1/25 image from [here ](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2025-10-02/)and selecting "Use Custom" to perform the image creation. This did not work.

**Comment by remonlam** [comment]
Yes same issue over here, tried 1.9.5, 1,9,6 and 2.0.0 but all had the same issue. So I think it's not related to the imager software but something with the latest release of Raspbian Trixie, because with Bookworm it's working just fine.

**Comment by lurch** [comment]
This sounds like a duplicate of #1320 ? (I tried replicating that issue yesterday: running Imager 2.0.0 and Imager 1.9.6 on an Ubuntu x64 PC, and booting the microSD card in a Raspberry Pi 500+, but it always "just worked" for me 😕 )

**Comment by remonlam** [comment]
@lurch will test it later today, let you know!

**Comment by bencunn77** [comment]
> This sounds like a duplicate of [#1320](https://github.com/raspberrypi/rpi-imager/issues/1320) ? (I tried replicating that issue yesterday: running Imager 2.0.0 and Imager 1.9.6 on an Ubuntu x64 PC, and booting the microSD card in a Raspberry Pi 500+, but it always "just worked" for me 😕 )

I had a glance through and obviously missed that to try and not duplicate

**Comment by remonlam** [comment]
Just tested it, the customizations are still not working with Imager v1.9.6 & v2.0.0 in combination with Debian Trixie, Bookworm is working fine.

**Comment by lurch** [comment]
Thanks for checking. What OS, SD card-reader and microSD card are you using with Imager @remonlam ?

**Comment by remonlam** [comment]
@lurch It's the Raspberry Pi 512GB SSD with a CM5 16GB Lite.
I'm imaging it on a Macbook running MacOS Tahoe 26.1, writing it via a USB-C PCIe dock.

**Comment by gbixa** [comment]
i had the same problem when using multiple ssh keys in a file. The yaml for cloudinit contained irregular newlines and the users section was then skipped.

**Comment by lurch** [comment]
> i had the same problem when using multiple ssh keys in a file. The yaml for cloudinit contained irregular newlines and the users section was then skipped.

Oooh, interesting! Thanks @gbixa that gives us something to investigate.

@remonlam Could you confirm which of Imager's customisation settings you are or aren't using please?

**Comment by remonlam** [comment]
@lurch sure, I arrange them here below.
All of them are not being applied.

General tab:
- Set hostname
- Set username and password
- Set local settings

Services tab:
- Enable SSH
- Use password authentication

Options tab:
- Unselect "Enable telemetry"

**Comment by lurch** [comment]
@remonlam Ahhh, those are the settings from the old 1.9.6 version of Imager. We won't be making any bugfixes to that 😉 
Please detail which customisations you're using in Imager 2.0.0.

**Comment by bakerhillpins** [comment]
@lurch - If it makes a difference, I'm on Win11, trying to setup a CM5. Attempted with all 3 versions Full/Lite/Std all with the same not working results.

We are using the following settings:

General tab:

    Set hostname
    Set username and password
    Set local settings

Services tab:

    Enable SSH
    Use password authentication

Options tab:

    Select "Eject media when finished"
    Un-select "Enable telemetry" and "Play Sound when finished"

**Comment by bakerhillpins** [comment]
> [@remonlam](https://github.com/remonlam) Ahhh, those are the settings from the old 1.9.6 version of Imager. We won't be making any bugfixes to that 😉 Please detail which customisations you're using in Imager 2.0.0.

It fails with either version here. 2 other users in the office attempted it with 2.0.0 and got the same results.

**Comment by remonlam** [comment]
@lurch correct I just re-tested it with 1.9.6, but I have the same issue with the newer version 2.0.0 and only in combination with Debian Trixie. The customization works fine with Debian Bookworm.

I could re-test with 2.0.0 if needed.

**Comment by tdewey-rpi** [comment]
On your booted device, could you please post the output of:

`cloud-init status --long`?

**Comment by remonlam** [comment]
@tdewey-rpi sure, here is the output.

```
$ cloud-init status --long

status: done
extended_status: degraded done
boot_status_code: enabled-by-generator
last_update: Thu, 01 Jan 1970 00:02:23 +0000
detail: DataSourceNone
errors: []
recoverable_errors:
WARNING:
	- Getting data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'> failed
	- DataSourceNoCloudNet  only uses seeds starting with ('http://', 'https://', 'ftp://', 'ftps://') - file:///boot/firmware is not valid.
	- Getting data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'> failed
	- Getting data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'> failed
	- DataSourceNoCloudNet  only uses seeds starting with ('http://', 'https://', 'ftp://', 'ftps://') - file:///boot/firmware is not valid.
	- Could not find module named cc_netplan_nm_patch (searched ['cc_netplan_nm_patch', 'cloudinit.config.cc_netplan_nm_patch'])
	- Used fallback datasource
```

**Comment by bakerhillpins** [comment]
@tdewey-rpi here's the output that I'm seeing. Running on a CM5/4GB.  I imaged the SD Card, connected monitor/keyboard/mouse, powered up, and then walked through the manual settings (which should have been applied during the imaging process but were not). After the settings, I skipped updates and launched the desktop. This is the output from the command:

``` 
$ cloud-init status --long
status: done
extended_status: degraded done
boot_status_code: enabled-by-generator
last_update: Thu, 01 Jan 1970 00:00:19 +0000
detail: DataSourceNoCloud [seed=ds_config_seedfrom,file:///boot/firmware][dsmode=local]
errors: []
recoverable_errors:
WARNING:
	- Failed at merging in cloud config part from part-001: empty cloud config
	- Failed at merging in cloud config part from part-001: empty cloud config
	- Failed at merging in cloud config part from part-001: empty cloud config
	- Could not find module named cc_netplan_nm_patch (searched ['cc_netplan_nm_patch', 'cloudinit.config.cc_netplan_nm_patch'])
```

**Comment by tdewey-rpi** [comment]
Thanks for the reports, @remonlam and @bakerhillpins 

In both cases, cloud-init abandoned using the configuration provided by Imager, but for different reasons:

In @remonlam's report, it appears that cloud-init started and failed to find `/boot/firmware`, which would predictably fail. This should probably be reported in the trixie-feedback repo, as there's nothing to indicate that Imager is the party at fault here.

In @bakerhillpins's report, it's possible that there's something invalid in the cloud-init file that is causing the YAML merge to fail early on. Cloud-init operates by composing layers of config one after the other - so a failure to parse can cause a failure to merge. It would be extremely useful to check the /boot/firmware/user-data, /boot/firmware/network-config, and /boot/firmware/meta-data files to confirm these aren't malformed. Try using a tool like `yamllint` to parse and verify the files.

**Comment by remonlam** [comment]
Hi @tdewey-rpi ok thanks for the clarification! I'll create a new issue in that repo and refer to this one.

**Comment by bakerhillpins** [comment]
@tdewey-rpi 
Online linter yamllint.com used:

/boot/firmware/user-data - valid, however the entire file is a comment (# in first column of every line)
/boot/firmware/network-config - valid, however the entire file is a comment (# in first column of every line)
/boot/firmware/meta-data - valid, reduces down to:

```
---
dsmode: local
instance_id: rpios-image
```

I can upload files if you want them.

**Comment by tdewey-rpi** [comment]
> [@tdewey-rpi](https://github.com/tdewey-rpi) Online linter yamllint.com used:
> 
> /boot/firmware/user-data - valid, however the entire file is a comment (# in first column of every line) /boot/firmware/network-config - valid, however the entire file is a comment (# in first column of every line) /boot/firmware/meta-data - valid, reduces down to:
> 
> ```
> ---
> dsmode: local
> instance_id: rpios-image
> ```
> 
> I can upload files if you want them.

Now that's _extremely_ unexpected. Did your write summary include customisations being applied?

Edit: To confirm, this was also with Imager 2.0?

**Comment by bakerhillpins** [comment]
@tdewey-rpi 
I've not moved forward to 2.0 as of yet, using 1.9.6, considering both were having issues. I can if you desire. 

> > [@tdewey-rpi](https://github.com/tdewey-rpi) Did your write summary include customisations being applied?

You're going to have to help me here. Don't know what this is or where to find this.

[edit] I will be unavailable tomorrow - Sorry.

**Comment by lurch** [comment]
@bakerhillpins As I mentioned earlier in this thread, we're not going to be fixing bugs in Imager 1.9.6 as all our attention is now on Imager 2.0. So yes, please upgrade and report back with your updated findings afterwards 🙂 

EDIT: The "write summary" in Imager 2.0 is this screen: https://www.raspberrypi.com/documentation/computers/getting-started.html#step-5-write-the-image-to-the-storage-device

**Comment by alexsapps** [comment]
Too bad the latest version of Pi Imager available via apt for me is 1.8.5+noembed-0ubuntu5 . I spent two hours trying to figure out what I was doing wrong while flashing the Pixie version of Pi OS with SSH/wifi settings. I fixed it by installing the legacy Pi OS based on Bookworm before I realized I was using an out of date version of the imager.

**Comment by alexsapps** [comment]
I requested ubuntu to add 2.0 here:
https://bugs.launchpad.net/ubuntu/+source/rpi-imager/+bug/2134313

**Comment by martignoni** [comment]
> /boot/firmware/meta-data - valid, reduces down to:
> 
> ```
> ---
> dsmode: local
> instance_id: rpios-image
> ```

I have exactly the same thing, using RPi Imager 2.0.0. And the write summary includes customisations being applied.

<img width="792" height="590" alt="Image" src="https://github.com/user-attachments/assets/3e46330a-fe90-4d96-ab88-3dc935fb245d" />

**Comment by bakerhillpins** [comment]
> [@bakerhillpins](https://github.com/bakerhillpins) As I mentioned earlier in this thread, we're not going to be fixing bugs in Imager 1.9.6 as all our attention is now on Imager 2.0. So yes, please upgrade and report back with your updated findings afterwards 🙂
> 
> EDIT: The "write summary" in Imager 2.0 is this screen: https://www.raspberrypi.com/documentation/computers/getting-started.html#step-5-write-the-image-to-the-storage-device

@lurch  
As I mentioned in previous comments, I was using 1.9.6 but others in our organization are using 2.0 and having the same issue. I'll see if I can get you some more information today using 2.0

**Comment by gitbls** [comment]
I installed a fresh RasPiOS Lite of 2025-12-04 the other day, and installed rpi-imager 2.0 on it, as well as my handy-dandy xterm.

Running on an xterm (displayed remotely) I ran `sudo rpi-imager` and provided the customization details (hostname, localization, username/password, WiFi) and wrote the disk after selecting Raspberry PI OS with Desktop for a Pi5.

Looking at the disk before booting, there is no user information in /boot/firmware/user-data, and of course when it boots, I'm (unsurprisingly) prompted for everything but the hostname, which IS in user-data

This appears to be highly reproducible.

Here's the output of cloud-init status --long after booting
```
status: done
extended_status: degraded done
boot_status_code: enabled-by-generator
last_update: Thu, 01 Jan 1970 00:00:15 +0000
detail: DataSourceNoCloud [seed=ds_config_seedfrom,file:///boot/firmware][dsmode=local]
errors: []
recoverable_errors:
WARNING:
        - Could not find module named cc_netplan_nm_patch (searched ['cc_netplan_nm_patch', 'cloudinit.config.cc_netplan_nm_patch'])
bls@mondo/l/work/sdm/dev-cloud-init> 
```
And here's /boot/firmware/user-init
```
hostname: pit
manage_etc_hosts: true
packages:
- avahi-daemon
apt:
  conf: |
    Acquire {
      Check-Date "false";
    };
timezone: America/Los_Angeles
keyboard:
  model: pc105
  layout: "us"
rpi:
  interfaces:
    serial: true
```

**Comment by gitbls** [comment]
@remonlam If your link to #46 is intended as a response for my comment, that link is irrelevant. There are no Macs in my house!

And, while I'm at it, I have done several more customizations trying to find even one incantation that works when running rpi-imager 2.0 on Trixie Lite or Trixie Desktop.

Unfortunately, each and EVERY time I boot an rpi-imager burned disk I end up having to go through the startup "add users and other config" dialog.

**Comment by remonlam** [comment]
@gitbls Nope I'm linking to a different issue (same number) in a other repo.

**Comment by tdewey-rpi** [comment]
Issue identified, resolved in $HEAD. I'm expecting to publish a 2.0.2-rc build later today that will contain the fix.

**Comment by remonlam** [comment]
@tdewey-rpi Nice, thanks for sharing, I will re-test it when I have time!

**Comment by bakerhillpins** [comment]
> [@tdewey-rpi](https://github.com/tdewey-rpi) Nice, thanks for sharing, I will re-test it when I have time!

Same

**Comment by remonlam** [comment]
@tdewey-rpi Just tested it but unfortunately it seems the customizations are still not being applied.
Using version 2.0.2 --> https://github.com/raspberrypi/rpi-imager/releases/tag/v2.0.2

Tried the following OS:
- Raspbian Trixie - 64 bit Lite (not working)
- Raspbian Bookworm - 64bit Lite (working)

<img width="792" height="594" alt="Image" src="https://github.com/user-attachments/assets/f92c319e-fd62-4fa0-b7e5-578625f7c76e" />

**Comment by bakerhillpins** [comment]
2.0.2 is working for us. I just used Trixie dated 2025-12-04

Hostname/Localization/user and psswd/enable SSH

**Comment by remonlam** [comment]
@bakerhillpins Interesting so it's working for you?

**Comment by gitbls** [comment]
I just did an `apt install rpi-imager_2.0.2_arm64.deb` and ran it. I changed the WiFi password bc I had given it a bogus password earlier. All customizations were applied, according to the Imager final screen. 

And, indeed, when I looked at the burned disk, /boot/firmware/user-data had the correct username/password, which were both AWOL previously.

However, when I booted the system it went into the "Welcometo the Raspberry Pi Desktop!" app. 

I then reburned the disk, and of course it booted correctly and completely to the desktop. So, 3rd time is a charm. I set the journal to be persistent, and when I look at the log after the boot has completed it looks like 'Started: cloud-init-main" and "Mounted bot-firmware.mount" are in a potential race condition. Here's the issue: https://github.com/RPi-Distro/rpi-cloud-init-mods/issues/2

Summary:  rpi-imager 2.0.2 Good to go IMHO. Issue WRT /boot/firmware being mounted is independent of this, but gooing to be a random reported issue until it's corrected.

**Comment by bakerhillpins** [comment]
> [@bakerhillpins](https://github.com/bakerhillpins) Interesting so it's working for you?

@remonlam 
Yes, downloaded 2.0.2 from [here](https://github.com/raspberrypi/rpi-imager/releases/download/v2.0.2/imager-v2.0.2.exe) and simply ran with the latest image with the customizations. Only burned 1 image so far though.

**Comment by tdewey-rpi** [comment]
Closing this:

- Multiple reports that 2.0.2 is behaving as-expected
- Remaining issues in this area are in rpi-cloud-init-mods, and will require a new image of Raspberry Pi OS to catch
